### ISSUE TITLE
Example request: Save the state of an react native Todo app

### ISSUE THREAD

**Issue by karthickvkumar** [michaelcontento/redux-storage#120]
Hi @michaelcontento, @xanderwebs and @greenkeeperio-bot,  thanks for this awesome library. It would be more helpful to understand the redux-store, if u provided some todo app, and store the app data. If you find some time please add a simple todo app with redux-store demo.

Thanks in Advance

**Comment by jeremymarc** [comment]
+1

**Comment by shichenda** [comment]
+1

**Comment by steida** [comment]
You can check https://github.com/este/este, my dev stack, where redux-storage is used both in browser and React Native.

**Comment by michaelcontento** [comment]
Sorry for the bad news but this package is no longer maintained. 😞 

My focus has left the react / node ecosystem and I don't have to time to keep things up to date. But if you want to step in and become the new maintainer of `redux-storage` and all of it parts, just ping me! 😃
