### ISSUE TITLE
Should the LOAD event be scoped to the reducer somehow?

### ISSUE THREAD

**Issue by seanadkinson** [michaelcontento/redux-storage#128]
When listening for the LOAD event, I'm given the entire state tree (as expected, I'm sure).  My question is: should I be scoped to my current reducer somehow?  In order for me to manipulate the state when loaded, I'd need to reach deep into the state tree, knowing all the paths of `combineReducers` above me.

I'm wondering if manipulating the state tree on LOAD is maybe an unsupported or discouraged use case.  What I'm trying to do is wrap certain parts of the state tree in custom model classes, which can't be persisted and retrieved wrapped in their model.  Is there a different recommended approach to achieve this?

Example state tree:
```
{
    auth: {
        user: new User({ id: 123, name: 'Sean' })
    }
}
```

This gets saved as:
```
{
    auth: {
        user: { id: 123, name: 'Sean' }
    }
}
```

So in my `auth` reducer, I **want** something like:
```
    [LOAD]: (state, action) => {
        return {
            ...state,
            user: new User(action.payload.user)
        };
    }
```

Or better yet:
```
    [LOAD]: (state, action) => {
        return {
            ...state,
            user: new User(state.user)
        };
    }
```

But instead, I must:
```
    [LOAD]: (state, action) => {
        return {
            ...state,
            user: new User(action.payload.auth.user)
        };
    }
```

Any knowing about the `auth` scoping is the part I don't like here.

Does that question make sense?  Is there a different recommended approach to something like this?

Thanks!

**Comment by michaelcontento** [comment]
Yes, I do understand your question and it makes total sense 😄 

Another way to handle this would be a custom merger, as it's the job of a merger to merge the current state with the one received by `engine.load` (see https://github.com/michaelcontento/redux-storage/blob/master/src/reducer.js#L8). But sadly this would only move your code around and **not** solve the scoping issue. But maybe it's a better organization if you put all the enhance-dicts-to-objects in one place?

But for now redux-storage does not have any deeper understanding of your state. But feel free to create a PR / API to change this! 😎
