### ISSUE TITLE
Blacklist based on keys instead of actions

### ISSUE THREAD

**Issue by woniesong92** [michaelcontento/redux-storage#134]
It is convenient to blacklist based on state keys instead of actions.
For example, is it possible to tell `redux-storage` to not store `router` into localStorage when the global state looks like below?

```json
state: {
  router: '...',
  currentUser: '...',
}
```

I am trying to make `redux-storage` not save `router` into localStorage. Doing so prevents the user from navigating the app by changing the url in his address bar.

**Comment by michaelcontento** [comment]
Yes, exactly this is the job of [redux-storage-decorator-filter](https://github.com/michaelcontento/redux-storage-decorator-filter) 😄
