### ISSUE TITLE
setTimeout around engine.save

### ISSUE THREAD

**Issue by dannybloe** [michaelcontento/redux-storage#142]
We are currently using redux-storage and are experiencing that it slows down our app quite significantly due to many writes (debouncing didn't help in our case). As a small experiment we put a setTimeout(.., 1000) around the engine.save() command because we only want to save stuff as soon as there is no UI thread doing anything. And lo and behold, that surely sped things up quite a bit. 

Would it be possible to have this as a feature and if not, are there complications?

Cheers, 

Danny

**Comment by michaelcontento** [comment]
But shouldn't [redux-storage-decorator-debounce](https://github.com/michaelcontento/redux-storage-decorator-debounce) be the right solution for you? 

```js
import debounce from 'redux-storage-decorator-debounce'
engine = debounce(engine, 1000);
```

Should have the same effect as your experiment, as `debounce` also uses `setTimeout` !?

**Comment by dannybloe** [comment]
/me scratches his head... and tries again

**Comment by michaelcontento** [comment]
😂

**Comment by dannybloe** [comment]
Doh.. we had a too-low debounce timeout value.  Ignore this :)

**Comment by dannybloe** [comment]
Ehm... is it possible to do a write on onBeforeUnload if it happens before the debounce timeout?

**Comment by michaelcontento** [comment]
You mean `window.onBeforeUnload`? Please file a bug with this at [redux-storage-decorator-debounce](https://github.com/michaelcontento/redux-storage-decorator-debounce)
