### ISSUE TITLE
Dispatch REDUX_STORAGE_SAVE only when state has been really changed.

### ISSUE THREAD

**Issue by steida** [michaelcontento/redux-storage#144]
From developer experience, it really makes sense to not dispatch REDUX_STORAGE_SAVE when nothing has been changed.

Update Engine save?

**Comment by michaelcontento** [comment]
I also like the idea but it would require a deep comparision of the state which might be a bit difficult, as the user free to put immutablejs or any other non-plain-old-javascript-object in the state.

**Comment by steida** [comment]
No at all.

> All Immutable Iterables also implement toJSON() allowing them to be passed to JSON.stringify directly.

https://github.com/facebook/immutable-js#converts-back-to-raw-javascript-objects

**Comment by michaelcontento** [comment]
I'm not saying it's impossible to implement 😃 

We also should think about where to add this check. Currently the middleware ([see here](https://github.com/michaelcontento/redux-storage/blob/master/src/createMiddleware.js#L88-L89)) is will trigger the action after `engine.save` resolves. If we add this check **before** calling `engine.save` we also skip the whole engine-decorator stack (which might be expensive too), but `redux-storage-decorator-filter` for example could increase the *"skip save hitrate"*.

**Comment by adamterlson** [comment]
I just discovered this issue myself and found that it results in, naturally, all of my `connect`ed components re-rendering, which in turn re-renders my stateless functional components (as they lack the componentShouldUpdate check).  This has resulted in a noticeable slowdown in the rendering performance of my react native app.

Are you aware of any work-arounds to this that can help alleviate the performance impact of the overly chatty REDUX_STORAGE_SAVE?

**Comment by michaelcontento** [comment]
Your `connect`ed components should only re-render as soon as the state changes. `REDUX_STORAGE_SAVE` is, on its own, just a simple action and **does not** change the state itself. So as long as you don't process and modify the save action, the state keeps the same and no component should start re-rendering.

Can you provide us some example code to illustrate this behaviour?

**Comment by adamterlson** [comment]
Ah, well, thanks for the intel!  Perhaps I have some other odd behavior going on!  Let me do some investigation on my end and I'll check back when I know more.

**Comment by cuitianze** [comment]
How can i trigger saving engine in custom http request file outside the component?
Scene： User had logined in app, however the server tell client that the user is not login, so i should change the localstorage.
Apologize for my poor english.

**Comment by cuitianze** [comment]
Sorry, i have known what i need, just use store function(dispatch actions) outside components.

**Comment by michaelcontento** [comment]
Sorry for the bad news but this package is no longer maintained. 😞 

My focus has left the react / node ecosystem and I don't have to time to keep things up to date. But if you want to step in and become the new maintainer of `redux-storage` and all of it parts, just ping me! 😃
