### ISSUE TITLE
This repo should be monorepo

### ISSUE THREAD

**Issue by steida** [michaelcontento/redux-storage#145]
There is really no benefit in having this as a bundle of several independent repos.
React, Este, Babel, and the others are mono repos for a good reason.

It would ease your work.

- https://github.com/babel/babel/blob/master/doc/design/monorepo.md
- http://danluu.com/monorepo/

**Comment by michaelcontento** [comment]
Yes, `redux-storage` and all it's official addons might be a monorepo. But as a manyrepo it's also not that difficult the handle - at the moment.
