### ISSUE TITLE
Why [REDUX_STORAGE_LOAD] change the state?

### ISSUE THREAD

**Issue by cuitianze** [michaelcontento/redux-storage#149]
![redux_storage_error](https://raw.githubusercontent.com/cuitianze/React-ReactNative-Redux_NOTEBOOK/master/asserts/images/%5BIssues%5D/redux_storage_error.png)

**Comment by michaelcontento** [comment]
Loading for `redux-storage` is simply a forwarding of the engine result ([see here][1]).

So the question for me here are:

1. Which engine do you use?
1. Are there any special decorators in place?
1. At which point in time are those logs written?
1. Can you provide some working code that illustrates / isolates the problem? 

Thanks a lot

  [1]: https://github.com/michaelcontento/redux-storage/blob/master/src/createLoader.js#L5-L6

**Comment by michaelcontento** [comment]
Closed as inactive. Feel free to re-open this issue if this is still a problem!
