### ISSUE TITLE
RFC add a CLEAR action

### ISSUE THREAD

**Issue by mattkrick** [michaelcontento/redux-storage#150]
Right now we've got LOAD and SAVE, but what happens if a person logs out? Chances are, we'll want a CLEAR.

Thoughts?

**Comment by mattkrick** [comment]
Yeah, I think the alternative is to write a null reducer & call `store.replaceReducer(nullReducer)`. It's not bad, but it's something I'd only ever do if I were persisting the state, so it'd be great to lift that out of the application logic & into the persist logic.

**Comment by michaelcontento** [comment]
But .. uhm .. well `replaceReducer` is an advanced API that you shouldn't need to bother with - most of the time. Especially for such a simple problem. 

I also don't fully understand your need for the null reducer solution. 
What is the problem your trying to solve? 
In my head the situation looks like this:

1. Given the user is logged in an the state is something like 

    `state = { user: { name: 'mat', loggedIn: true } }`
    * **Note**: We assume that this state is also currently known to `redux-storage`
1. Now the user logs out and a `USER_LOGOUT` action is dispatched
1. Someone (usually the `UserReducer`) is triggered by the `USER_LOGOUT` action 

    `state = { user: null }`
1. The changed state will be detected by `redux-storage` and written to the engine
1. Done

And this behaviour sounds pretty sane to me 😄

**Comment by jordanh** [comment]
In @mattkrick's case, we are using `store.replaceReducer()` to dynamically load different reducers between routes. We're [building a fairly complex app](https://github.com/ParabolInc/action).

When we hit our logout route, it won't be clear what information we want to expunge from the store...but, we want to get it all. We're trying to avoid leaving one user's private information in the store and having it available to another if they switch accounts when using the same web browser.

@mattkrick: I think `store.replaceReducer(...)` with reducer that's built from a whitelist is probably the way to go. I think @michaelcontento's point of `redux-storage` is just a mirror (roughly paraphrasing) makes sense...

**Comment by mattkrick** [comment]
that definitely works for 1 reducer that you own, but for fun let's say you have 8 reducers: some you own, some are 3rd party, some are loaded initially, some are asynchronously added via [webpack magic + replaceReducer](https://github.com/ParabolInc/action/blob/master/src/universal/routes/welcome.js#L22-L23).

For example, you have a reduxForm reducer & you persist some form data. If their browser crashes, you are a rockstar because the boot back up to a their form half filled out. That's awesome! But if they click log out, you should probably clear their half-finished form because it has sensitive info & they're at a public computer.

It's not enough to just null out the reducer (`state.reduxForm = undefined`), rather you'll need to `delete state.reduxForm` since your initial reducer doesn't know about it.

**Comment by mattkrick** [comment]
@jordanh whoa same time! yeah, let's just null out the entire thing, & then replace the nullReducer with an initialReducer so it's the same as a refresh.

**Comment by michaelcontento** [comment]
Well there is always the `engine.save({})` sledgehammer 😉

**Comment by mattkrick** [comment]
^^^^ ***that!*** ^^^^ 
let's go with that. sledgehammers get stuff done!

**Comment by michaelcontento** [comment]
Note that this would only solve a potential information leak through `redux-storage`. And **ONLY** up until a new action triggers a new `engine.save`!

This is important to remember: `redux-storage` is the "persistence layer behind `redux`". So if your unable to fully clear/reset the state within redux there is still a possible information leak. And those informations might also be stored through `redux-storage` at any time in the future.

Only `engine.save({})` with a immediate full redux-stack reload (possible by a browser refresh) would solve the information leak on all layers.

**Comment by jordanh** [comment]
Ha. We're having this same conversation on our internal Slack right now!

**Comment by michaelcontento** [comment]
Did you find a final solution you're happy with? If so, would it be possible to share it with us? 😄 

Oh, and please close this issue if there is nothing `redux-storage` can do for you 👼

**Comment by jordanh** [comment]
We're still finalizing some of the finer details, but in general I think we found a solution we're happy with.

We ended up not using the sledgehammer pattern `engine.save({})` for reasons related to what you mentioned above. Instead we're clearing our redux state and letting `redux-storage` do its job of acting like a mirror.

Our application dynamically loads reducers from within `react-router` as they are needed. We have a single logout route that revers our reducers to a pre-calculated initial redux state:

```javascript
import {makeInitialStateReducers} from 'universal/redux/makeReducer';

const reducerWhitelist = [
  'notifications'
];

export default (store) => ({
  path: '/logout',
  getComponent: async(location, cb) => {
    const component = await System.import('universal/containers/Logout/LogoutContainer');
    const newReducer = makeInitialStateReducers(reducerWhitelist);
    store.replaceReducer(newReducer);

    cb(null, component);
  }
});
```

You can see the full implementation here [in this PR to our application](https://github.com/ParabolInc/action/pull/157/files).

I'll leave it up to @mattkrick to close this issue.

**Comment by mattkrick** [comment]
yep, all good over here. Thanks for putting up with me while we found a good pattern!

**Comment by jordanh** [comment]
(deleted our original solution, posting a new one)

Originally we were going to replace our dynamically loaded reducers but in the end went with a much simpler, much more redux-y solution.

After reading [this Stackoverflow](http://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store) answer, we ended up wrapping our combined reducers in a new rootReducer that can reset application state.

Now we we log out, we simply dispatch the reset action and let `redux-storage` act as a mirror.

Details are in [this PR](https://github.com/ParabolInc/action/pull/157) from our repository.
