### ISSUE TITLE
How do you deal with app updates?

### ISSUE THREAD

**Issue by kevando** [michaelcontento/redux-storage#157]
I am rather new to app development, but I keep running into issues when beta testers update the app. I change the state tree quite heavily - which is causing most of the problems. 

a) Is there a better approach to that?
b) Where would you place a check to run `engine.save({})` if the app is updated?

**Comment by michaelcontento** [comment]
Hi,

changing the state tree on every update will always cause some trouble. The best solution would be to minimize such changes and use data structures / layouts that allow future changes without breaking on the very first change. 

Beside that, [redux-storage-decorator-migrate](https://github.com/mathieudutour/redux-storage-decorator-migrate) might be a good companion for you. Also your reducers could handle the [LOAD / SAVE](https://github.com/michaelcontento/redux-storage#actions) and transform / update accordingly.

Feel free to re-open this issue if questions are left open!

**Comment by kevando** [comment]
Thanks @michaelcontento  I will check that out migrate package. That closes this question, but I do have one more thing I'm trying out.

Do you know if [Redux ORM](https://github.com/tommikaikkonen/redux-orm) will work with your redux-storage?

**Comment by michaelcontento** [comment]
I haven't tested `redux-storage` with `redux-orm` as your post is the first thing I hear about `redux-orm` 😂 

But I builds on top of `redux` and as long as it follows the api / design / contract of `redux` (which it does - as far as I can tell after a quick look) `redux-orm` and `redux-storage` should play together nicely 😃
