### ISSUE TITLE
How to only persist certain parts of state? 

### ISSUE THREAD

**Issue by brandonfujii** [michaelcontento/redux-storage#160]
Is there a way to exclude certain parts of state from storage?

**Comment by maluramichael** [comment]
What is the solution to this?

**Comment by brandonfujii** [comment]
@maluramichael I would suggest using an engine decorator like: https://github.com/michaelcontento/redux-storage-decorator-filter. With it, you'd be able to blacklist certain parts of your storage.

**Comment by maluramichael** [comment]
@brandonfujii nice. thank you.
