### ISSUE TITLE
State lost when browser refreshed more than once

### ISSUE THREAD

**Issue by anandrikka** [michaelcontento/redux-storage#162]
Hello,

This is how I'm using redux-storage in my store.js

`let reducer = storage.reducer(rootReducer);
let engine = createEngine('my-save-key');
let engineMiddleware = storage.createMiddleware(engine);

let middleware = applyMiddleware(thunk, logger(), engineMiddleware);

let store = createStore(rootReducer, middleware);

let load = storage.createLoader(engine);
load(store);`

I'm getting data from local storage for 1st time. However from 2nd time when I refresh browser  data is lost and no more gets the state

**Comment by michaelcontento** [comment]
Sorry for the bad news but this package is no longer maintained. 😞 

My focus has left the react / node ecosystem and I don't have to time to keep things up to date. But if you want to step in and become the new maintainer of `redux-storage` and all of it parts, just ping me! 😃

**Comment by michaelcontento** [comment]
Re-opened as @guns2410 want's to work on this project: Give him a warm welcome 👏

**Comment by guns2410** [comment]
Thanks @michaelcontento 

@anandrikka can you check if there are any errors loading the state.

``` javascript
load(store)
    .then((newState) => console.log('Loaded state:', newState))
    .catch((err) => console.log(err));
```

**Comment by anandrikka** [comment]
Thanks @michaelcontento  for taking time
