### ISSUE TITLE
es6 / rollup / require is undefined

### ISSUE THREAD

**Issue by duydao** [michaelcontento/redux-storage#168]
I'm having problems loading redux-storage as es6-module with rollup.js in ionic. The generated code for https://github.com/michaelcontento/redux-storage/blob/master/src/index.js#L6-L12 (build-es/index.js) throws an error in the browser:

``` javascript
// The full default export is required to be BC with redux-storage <= v1.3.2
export default _extends({}, require('./constants'), {
    createLoader: require('./createLoader')['default'],
    createMiddleware: require('./createMiddleware')['default'],
    reducer: require('./reducer')['default']
});
```

Removing that part from the generated file will resolve this problem. Is this code still required?

**Comment by michaelcontento** [comment]
Sorry for the bad news but this package is no longer maintained. 😞 

My focus has left the react / node ecosystem and I don't have to time to keep things up to date. But if you want to step in and become the new maintainer of `redux-storage` and all of it parts, just ping me! 😃

**Comment by michaelcontento** [comment]
Re-opened as @guns2410 want's to work on this project: Give him a warm welcome 👏

**Comment by guns2410** [comment]
Thanks @michaelcontento 

@duydao can you confirm if `rollup-plugin-commonjs` resolves your issue.

I was able to find an [issue](https://github.com/rollup/rollup-plugin-commonjs/issues/77) on rollup.js

**Comment by duydao** [comment]
pretty sure it happened with 5.0.4, but ionic jumped the ship and is using webpack now. Thanks looking into it though!
