### ISSUE TITLE
storage is not defined

### ISSUE THREAD

**Issue by klausbreyer** [michaelcontento/redux-storage#28]
hi there, 

I am relativly new to react native AND redux, sadly. But I want to master this and I wanted to implement your redux-storage. 

As I want to implement this, I do not understand where storage comes from. You don't import it at the top. 

So I end up with an storage is not defined error. 

I defined my Reducer like this: 

```
const Reducer = createReducer([], (state, action) => {
    switch (action.type) {

        case ActionTypes.addAthlete:

...
```

```
const configureStore = function configureStore(initialState) {
    return createStore(Reducer, initialState);
};
```
```
module.exports = {
    configureStore: configureStore,
    Actions: Actions
};
```

Can you help me? :) Thanks in advance!

**Comment by michaelcontento** [comment]
Hi,

`storage` is just the result of importing this library. So it's easy as `import storage from 'redux-storage'` :smile: 

But you found a good point and I've updated the README.md about this (see: 67bb83cee68b4b254fd705569619130dcc3888bd). Thank you! :+1:
