### ISSUE TITLE
Handling multiple users

### ISSUE THREAD

**Issue by rnsloan** [michaelcontento/redux-storage#48]
Was looking to use this for a product with user accounts (not saving anything confidential), but I am thinking it is not suitable due to you defining the engine key and to load existing state at the application initialisation. If you have multiple users logging into the same machine you will not be able to load the correct data after they have logged in.

Or do you have suggestions on how to handle this scenario?

**Comment by michaelcontento** [comment]
Your scenario is possible but requires some more details about how your going to structure your state tree. Without any further knowledge or detailed thinking there are two solutions popping in my head right now.

### One state tree with a "pointer"

You could, for example, store everything in one state tree and use a "pointer" that's referring to the current one:

```js
const state = { 
    account: {
        "a@user.com": { name: "Hans Peter" },
        "b@example.com": { name: "Someone Else" }
    },
    currentUser: "b@example.com"
};
```

To handle such a tree https://github.com/rackt/reselect might be a good companion :)

### Create a custom engine

You're right that the key use by the engine is currently not changeable from the outside. But if you need this flexibility - just add it :) 

Take a look at the [localStorage engine](https://github.com/michaelcontento/redux-storage/blob/master/src/engines/localStorage.js) for example. There you only need a new method roughly like `setEngineKey(newKey) { key = newKey; }` and a switch could look like:

```js
// App Start
import createEngine from 'myLocalStorageEngine';
const engine = createEngine('initial-save-key');

const load = storage.createLoader(engine);
load(store); 

// User Switch
engine.setEngineKey('something-else');
load(store)
```

But keep in mind that `redux-storage` merges the old with the new state tree! You might have to clear/reset the current user right before loading the other one!

**Comment by michaelcontento** [comment]
Please close this issue if this does solve your question. If not, keep on asking :)

**Comment by rnsloan** [comment]
Thanks for the suggestions. I think I am going to need to code my own solution for this. Looking at the various redux storage packages they all seem to do the initial setup when creating the store. I need to load/create the external store after a user has logged in (probably around the same place a USER_LOGIN_SUCCESS action is dispatched once it receives a successful login response from the server). 

I could probably have the saving part as middleware but the loading part would need to be in an action creator at the point where I have the logged in users details to use/define the correct external storage key.
