### ISSUE TITLE
Versioned storage with migrations

### ISSUE THREAD

**Issue by steida** [michaelcontento/redux-storage#49]
Hi,

I am just curious if you thought about store migrations? What if we change structure? I think it should be responsibility of every reducer reviver.

**Comment by michaelcontento** [comment]
Hi,

currently there is no built-in functionality to handle migrations at all. But it should be pretty easy to create a custom engine decorator for this purpose. Here is a short (untested!) draft:

```js
// The engine as you like
import createEngine from 'redux-storage/engines/reactNativeAsyncStorage';
let engine = createEngine('my-save-key');

// Now add the new migrations decorator
import migrationDecorator from './migrationDecorator';
engine = migrationDecorator(engine, 'v3');
engine.addMigration('v1', (state) => { /* migration step for v1 */ return state; });
engine.addMigration('v2', (state) => { /* migration step for v2 */ return state; });
engine.addMigration('v3', (state) => { /* migration step for v3 */ return state; });
```

All you have to do in the `migrationDecorator` is to ....
- store the current version (second argument to `migrationDecorator`) in the state tree on `save()`
- compare the current version with the loaded one on `load()`
- apply all required migration callbacks 

So for the example in the draft above: if the current version is `v3` and the loaded one is `v1`, we need to apply callbacks for `v2` and `v3`.

Is this a good starting point for you? 

Feel free to submit such a decorator as a PR! I'm thankful for every contribution :)

**Comment by steida** [comment]
Awesome answer, thank you! Once I will implemented it, I will send you a PR.

**Comment by michaelcontento** [comment]
Thanks! I'll close this issue for now :)

**Comment by steida** [comment]
Here is it: https://gist.github.com/steida/f5e53c69c4e3b423c15d

Unfortunately, because `cognitive overhead`, I'm not able to send PR for
```
indent_size = 4
indent_style = space
```

Two spaces ftw.

**Comment by michaelcontento** [comment]
Re-opened as a reminder. If someone want to contribute @steida's gist as a PR, I'd be very happy :smiley:

**Comment by steida** [comment]
That's what I am using https://gist.github.com/steida/85443aac1dcb6daaa245 No time to send PR yet, maybe later :-)
