### ISSUE TITLE
Importing constants not working

### ISSUE THREAD

**Issue by victornguyen** [michaelcontento/redux-storage#51]
In the README's "Actions" example:
```js
import { LOAD, SAVE } from 'redux-storage';
```
Importing the constants in this way doesn't work as they are exposed as properties of the default export object, rather than as named exports.

I've gotten around this with something like:
```js
import storage from 'redux-storage';
const { LOAD, SAVE } = storage;
```

We could either:

1. Update the README example, or
2. Change the way the constants are exported

What do you think?

**Comment by michaelcontento** [comment]
Thank you for reporting this!

It broke with switching from babel@5 to babel@6 ([more details](https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default/33506169#33506169)) :cry: 

But I've been able to:
- fix this bug
- updated the README to encourage `import * as storage from 'redux-storage'` for full imports
- but also keep the old behaviour `import storage from 'redux-storage'`

A new version (`v1.3.4`) is already published to npm :rocket:

**Comment by victornguyen** [comment]
Awesome :tada:

Thanks for providing such a comprehensive solution!
