### ISSUE TITLE
throws TransformError in ReactNative 0.16

### ISSUE THREAD

**Issue by iZaL** [michaelcontento/redux-storage#65]
package throws TransformError in ReactNative 0.16

**Comment by sslash** [comment]
+1 
believe this is because it uses .babelrc. Similar issue here: https://github.com/goatslacker/alt/issues/558

**Comment by kdoh** [comment]
From what I understand it seems to be that ReactNative 0.16's use of Babel 6 makes it angry at some .babelrc files. 

Its not a particularly elegant solution, but using this script, which removes .babelrc files in the node_modules directory  https://github.com/alinz/example-react-native-redux/blob/master/Counter/package.json#L7 seems to work.

**Comment by michaelcontento** [comment]
`.babelrc` has already been excluded from the archive uploaded to npm. But with a52524fb59089ae5df674f354fb38cafac099823 I've removed the file at all. Does this solve this issue?

**Comment by iZaL** [comment]
yes, tnx

**Comment by sslash** [comment]
I am now getting an error saying cannot find preset "michaelcontento" relative to directory ....

**Comment by anderson916** [comment]
@sslash  I have the same issue.

**Comment by anderson916** [comment]
<img width="377" alt="2016-01-19 6 04 55" src="https://cloud.githubusercontent.com/assets/195719/12415549/3b33f870-bed7-11e5-8263-8abbc858fef2.png">

**Comment by anderson916** [comment]
Very strange. I got the same error even after I installed *babel-preset-michaelcontento*

**Comment by michaelcontento** [comment]
I've now created new projects for various versions of react-native (`0.16.0`, `0.17.0` and `0.18.0`) without any success in reproducing this error :disappointed: 

@anderson916 or @sslash: Would it be possible for you to create and publish a sample repository where I can see this error myself?

**Comment by michaelcontento** [comment]
This bug exists because of https://github.com/facebook/react-native/issues/4062. With PR #74 the babel config is back in its own file (`.babelrc`) which is ignored for the package published on npm. So if you install `redux-storage` via npm there is no more babel config that could fail :smile:

**Comment by anderson916** [comment]
It works now. @michaelcontento Thank you very much.

**Comment by michaelcontento** [comment]
No problem - a new version will be published to npm in a few minutes
