### ISSUE TITLE
ReactNative - JS load error

### ISSUE THREAD

**Issue by latusaki** [michaelcontento/redux-storage#72]
I have installed redux-storage using npm install and also made sure to rebuilt app etc.

When I have the following line in my redux store, the JS fails to load:

`import createEngine from 'redux-storage/engines/reactNativeAsyncStorage';`

I tried emulator and physical device, and both give error: 'Unable to download JS bundle.Did you forget to start the dev server...' 

If I take out that line and reload js,  the app works normally. This is with the folliowing dependencies:

```
  "dependencies": {
    "immutable": "=3.7.6",
    "react": "=0.14.3",
    "react-native": "=0.16.0",
    "react-native-radio-buttons": "^0.8.0",
    "react-redux": "=3.1.2",
    "redux": "=3.0.5",
    "redux-storage": "^1.4.3",
    "underscore": "^1.8.3"
  },
```

Any suggestions of what might be causing this ?

**Comment by michaelcontento** [comment]
I'm unable to reproduce this error. But `Unable to download JS bundle.Did you forget to start the dev server..` sounds like `react-native` is unable to fetch the JS bundle from your local machine.

Is the host/port configuration properly set and reachable? Or maybe the `react-native` packager has some problems with your setup? Can you spot anything in the output of the packager?

**Comment by latusaki** [comment]
This should be somehow related to redux, as by removing it I no longer had the problem. I have now upgraded to 0.18, will try to retest as soon as possible.

**Comment by michaelcontento** [comment]
I've tried to reproduce this error with various versions of `react-native` without any success :disappointed: 

And as long as we don't have any more detailed informations about the error there is nothing I could do here, therefore closed. But feel free to re-open this issue if you have new details at hand!
