### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by anderson916** [michaelcontento/redux-storage#76]
Thanks for this useful lib. Since this library stores the whole state tree into one key-value pair, the performance will decrease greatly if we put too much data into the state tree. So what's the best approach to improve the performance when using too much data?

**Comment by michaelcontento** [comment]
There are a lot of thing you could do to improve the performance:

- Use [decorators.filter](https://github.com/michaelcontento/redux-storage#filter) to trim the state tree before saving
- Use [decorators.debounce](https://github.com/michaelcontento/redux-storage#debounce) to collect / limit the amount of save operations done in a given timeframe
- Use the [black- and/or whitelist](https://github.com/michaelcontento/redux-storage#middleware) to only save if required 
- Create a new engine that operates async ([localForage](https://github.com/mozilla/localForage) could be a good backend to create a alternative to [engines.localStorage](https://github.com/michaelcontento/redux-storage#localstorage))

Another idea would be to create a new engine that stores the state tree in multiple key-value pairs. But I'm not sure that this would be a great improvement, as `JSON.stringify` / `JSON.parse` should be pretty fast (even for huge state trees!) and you would need to load&merge multiple keys for every load operation.

**Comment by michaelcontento** [comment]
Please close this issue if this answers your question. If not, keep on asking :smile:

**Comment by anderson916** [comment]
Very good. Thanks.
