### ISSUE TITLE
blacklist doesn't work

### ISSUE THREAD

**Issue by anderson916** [michaelcontento/redux-storage#82]
I used the following code to exclude those actions. The strange thing is: TAB_CHANGE, SEGMENT_CHANGE don't trigger SAVE action, but DOWNLOAD_UPDATE action still triggers SAVE action. The difference between them is: DOWNLOAD_UPDATE action is very frequent.

```
const middleware = storage.createMiddleware(engine, [
  actionTypes.TAB_CHANGE, 
  actionTypes.DOWNLOAD_UPDATE,
  actionTypes.SEGMENT_CHANGE])
```

**Comment by anderson916** [comment]
I add several console.log to debug this issue.
```
                var isOnBlacklist = blacklistedActions.indexOf(action.type) !== -1;
                var isOnWhitelist = actionWhitelist.length === 0 ? true // Don't filter if the whitelist is empty
                : actionWhitelist.indexOf(action.type) !== -1;

                console.log(blacklistedActions)
                console.log(action.type)
                console.log(isOnBlacklist)            
```

The following is my observation:

<img width="960" alt="2016-01-22 9 10 59" src="https://cloud.githubusercontent.com/assets/195719/12499740/211400b2-c0e8-11e5-8290-05da52810ff2.png">

**Comment by anderson916** [comment]
Then I output that extra action:

<img width="578" alt="2016-01-22 9 16 31" src="https://cloud.githubusercontent.com/assets/195719/12499825/e31fb282-c0e8-11e5-9ef5-68ac91d8dbb0.png">

**Comment by anderson916** [comment]
The workround is check if the action type is undefined:

```
                var result = next(action);

                if (! action.type)
                    return result
```

**Comment by michaelcontento** [comment]
Thank you for reporting this!

With 4a12182 redux-storage will now a) ignore invalid structured action objects and b) warn about them if `NODE_ENV != 'production'`.
