### ISSUE TITLE
Splitting the decorators from the core

### ISSUE THREAD

**Issue by mathieudutour** [michaelcontento/redux-storage#88]
Right now, when using this package without immutable, it will still require immutablejs which is quite big.

Each decorators should be required separately or be in its own package.

**Comment by michaelcontento** [comment]
Good point! Which solution do you prefer?

1) Own require for decorators (similar how we handle engines currently)
2) Like 1) but only for the immutable decorator
3) Move all decorators into own packages
4) Move all decorators **and** all engines into own packages

**Comment by mathieudutour** [comment]
Own require for decorators is the solution demanding the less work I think. I quite like it, it keeps the package.json clean

**Comment by michaelcontento** [comment]
I'm currently unsure. Yes, own require would be very easy. But as we're about to introduce a breaking API change, I'm willing to go a few more steps :smiley: 

IMHO solution 4) would be the cleanest. We would also get proper dependency support for `redux-storage/engines/reactNativeAsyncStorage`.

**Comment by mathieudutour** [comment]
Good point

**Comment by alizbazar** [comment]
👍
